### PR TITLE
Implement notesInfo

### PR DESCRIPTION
**Pull request by Aquafina-water-bottle**
TODO:
- Refactor the code? Private internal classes or move them to different files?
- Shouldn't have null returns / continues. If a note id is not found, it should result in an empty JSON object.

Depends on #43

### CODE REVIEW

**Comment by precondition** [comment]
After a small update to the Anki Android API dependency, I managed to build this version and it seems to work well enough to solve the issue raised in #50. Since it seems like Aquafina is no longer active, I forked the repo and posted a [release with a built apk file](https://github.com/precondition/AnkiconnectAndroid/releases/tag/v1.13-notesInfo). If you're reading this and are interested in fixing Mokuro image exports on mobile, check it out.

**Comment by KamWithK** [comment]
> After a small update to the Anki Android API dependency, I managed to build this version and it seems to work well enough to solve the issue raised in #50. Since it seems like Aquafina is no longer active, I forked the repo and posted a [release with a built apk file](https://github.com/precondition/AnkiconnectAndroid/releases/tag/versionCode13-notesInfo). If you're reading this and are interested in fixing Mokuro image exports on mobile, check it out.

Hey sorry for the late reply, been busy with a new job
This PR involves a large amount of change to the codebase iirc, which isn't necessarily bad but does mean that it needs a more thorough review and test than for most changes/features

If you/others have used this a lot are there any problems, bugs or oddities which you've encountered?

**Comment by precondition** [comment]
> If you/others have used this a lot are there any problems, bugs or oddities which you've encountered?

@KamWithK I'm not sure if it is related yet, but I've noticed that despite setting up a local audio server which works when using the audio button in the Yomitan pop-up, my Anki cards do not pick up the local audio and fall back to the default online JapanesePod server instead. Consequently, all the cards I mine while offline are missing word audio.

Apart from that, adding pictures to my last Anki card via mokuro files works well.

**Comment by KamWithK** [comment]
> > If you/others have used this a lot are there any problems, bugs or oddities which you've encountered?
> 
> @KamWithK I'm not sure if it is related yet, but I've noticed that despite setting up a local audio server which works when using the audio button in the Yomitan pop-up, my Anki cards do not pick up the local audio and fall back to the default online JapanesePod server instead. Consequently, all the cards I mine while offline are missing word audio.
> 
> Apart from that, adding pictures to my last Anki card via mokuro files works well.

Would you be able to check whether it's actually a problem with this new pr version or whether the latest release also has the same problem for you?

**Comment by KamWithK** [comment]
> > > If you/others have used this a lot are there any problems, bugs or oddities which you've encountered?
> > 
> > 
> > @KamWithK I'm not sure if it is related yet, but I've noticed that despite setting up a local audio server which works when using the audio button in the Yomitan pop-up, my Anki cards do not pick up the local audio and fall back to the default online JapanesePod server instead. Consequently, all the cards I mine while offline are missing word audio.
> > Apart from that, adding pictures to my last Anki card via mokuro files works well.
> 
> Would you be able to check whether it's actually a problem with this new pr version or whether the latest release also has the same problem for you?

@precondition did you ever give that a try?

**Comment by naiza-asaad** [comment]
> > > If you/others have used this a lot are there any problems, bugs or oddities which you've encountered?
> > 
> > 
> > @KamWithK I'm not sure if it is related yet, but I've noticed that despite setting up a local audio server which works when using the audio button in the Yomitan pop-up, my Anki cards do not pick up the local audio and fall back to the default online JapanesePod server instead. Consequently, all the cards I mine while offline are missing word audio.
> > Apart from that, adding pictures to my last Anki card via mokuro files works well.
> 
> Would you be able to check whether it's actually a problem with this new pr version or whether the latest release also has the same problem for you?

I think I have this issue too on the latest release. When I click on an audio from the popup list, a request like this is called: `http://localhost:8765/localaudio/shinmeikai8/media%2F16413.opus`

But when I click the add card button, this gets called instead: `http://localhost:8765/localaudio/shinmeikai8/media%252F16413.opus`

`LocalAudioAPIRouting.getAudioHandleError()` fails to find the audio in the db for this request. The quickest fix is to decode the path but I guess it's better to look at why Yomitan is sending a different request?

**Comment by KamWithK** [comment]
Given that @Aquafina-water-bottle has been gone for a long while and #60 is in a good state, I'm going to close this PR

**Pull request closed without merging**
